### ISSUE TITLE
Problem with no input at all on specific games e.g. fifa 97 (snes9x2002)

### ISSUE THREAD

**Issue by Linkinsoldier** [kodi-game/game.libretro.snes9x2002#3]
Preconditions:

0) Connect Controller (PS3 Bluetooth)
1) Start IARL
2) Choose SNES Games -> FIFA97 (or Fifa Soccer 97)
3) Start game with snes 9x2002 emulator

Excpected behaviour:
Playing game is possible with this controller

Seen behaviour:
No Controller could be used in game. Even connecting all other 3 controllers (to check issue #2 )
did not help

Remark: interesting enough the Controller work without issues on other games with the same emulator (e.g. NBA hang time!)

[kodi.zip](https://github.com/kodi-game/game.libretro.snes9x2002/files/785663/kodi.zip)

See attached log for more details

**Comment by ghost** [comment]
Same issue here.

The controller appears to be falling back into a "player 2" position when connected in conjunction with any other peripherals. Issue is not present in Libretro builds using udev as preference.

**Comment by ghost** [comment]
Just to add to the above, PS3 controller is connecting under js1 whilst keyboard/remote is connecting to js0. Retroplayer is not recognising js1 as player one default.

**Comment by garbear** [comment]
I've added a udev driver, but it's not the default because I was receiving rare crash reports right before the 17 release.

![](https://cloud.githubusercontent.com/assets/531482/24831276/cdf80a66-1c4b-11e7-8aee-5102c87d447b.png)

You can access this via Settings -> System -> Input -> Driver Settings -> Joystick Support (after #11944 was merged 3 weeks ago) or from the add-on manager (find Joystick Support and select Configure).

The plan was to make udev the default after the release. That came and went :) I'll do some more testing and change the default to udev when I get a chance.

Another solution would be a "player manager". I've started a forum thread [here](http://forum.kodi.tv/showthread.php?tid=295463), but I need a more concrete plan before I start coding.

**Comment by ghost** [comment]
Thanks garbear, Player manager looks like a fantastic idea.
I'm on Libreelec nightlies so will test as soon as the packages are rebuilt.

**Comment by garbear** [comment]
Input has been completely overhauled with the inclusion of my [Controller Topology Project](https://github.com/kodi-game/controller-topology-project). Is this issue fixed in the latest test builds?

**Comment by Linkinsoldier** [comment]
@garbear: I just retested this and unfortunately i still can't play fifa 97 via IARL. This might be connected to IARL, but I can't verify or falsify this unfortunately.

Controller works like a charm with snes 9x2002 with all games I have.

**Comment by garbear** [comment]
Have you tried going through the Advanced Settings in the OSD settings menu? I have report of this fixing input for a PS1 emulator.

I can see from your log that SNES button presses are sent to the core. To verify, input works for other games, but not for a select few? This sounds like a core issue, which I'll have to catch in a debugger.
 I hear some games break in the presence of a multitap, maybe these games require one?

**Comment by Linkinsoldier** [comment]
not sure I get what you are saying but after loading the rom (not being able to control) i pressed PS button to get into "OSD Menu" and tried to reset the button mapping. Mapping worked, however still no control. Even "resetting" the mapping didnt help.

I am sure it is due to the game - I tried all 4 Fifa games, no luck!

When starting puzzle booble, everything is fine :)

**Comment by garbear** [comment]
Do the revelations [here](https://forum.kodi.tv/showthread.php?tid=173361&pid=2768164#pid2768164) apply to your issue?

**Comment by Linkinsoldier** [comment]
there are no configurations possible for snes 2002. However I just tested snes 2010 emulator, and that still works without issues. So it really depends on whether you want this issue to be open or not. For me, using snes 2010 is a good solution!

**Comment by garbear** [comment]
Can this be closed?
